name: 🚀 Deploy resume.json

on:
  push:
    branches:    
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy at https://lebenslauf.vreezy.de
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: 🔨 Test Project
      run: |
        npm install
        npm run test

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: vreezy.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        state-name: .ftp-deploy-sync-backend-state.json
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          getSchema.js
          package*
          readme*
       
